### ISSUE TITLE
Array of objects sending '[object Object]' to controller

### ISSUE THREAD

**Issue by PeteAshworth** [diegohaz/bodymen#1]
I have the following field being send to node app (created off your generator btw)

```
links: [{'icon':'path to icon'}]
```

but once it gets to the controller, it fails due to its converted to '[object Object]'.  Confirmed that the array of object is correct if I remove the 

```
body({ links })
```

Suggestions or bug?  Thanks

**Comment by diegohaz** [comment]
Hi, @PeteAshworth 

What is the value of `links` (the one you send as argument to `body`)?

**Comment by PeteAshworth** [comment]
Maybe I should dive deeper to understand the package, but here is what I have currently.
>Mongoose Model
```
links: [{
    icon: String,
    url: String
  }]
```
>Route
```
const { ... links } = schema.tree
...
router.put('/', body({links})
```

I tried the type: Object within the route body() which gave me `[ '[object Object]' ]`

**Comment by diegohaz** [comment]
Oh, I can reproduce it. I'll investigate what is happening. Good catch.

**Comment by PeteAshworth** [comment]
Cool; Thank you!

**Comment by diegohaz** [comment]
Can you please do a fresh `npm install` and change `body({ links })` to `body({ links: [Object] })`?

It should work now.

**Comment by PeteAshworth** [comment]
Thanks for the quick fix.  Doing as suggested, I can console log the links and its now showing correctly.  Saving it into mongo is a different story (back to [object Object]) but willing to bet its with the _.merge(). 

Thanks again!

**Comment by PeteAshworth** [comment]
all working.  Thank you!

**Comment by diegohaz** [comment]
Yay! 🎉

**Comment by tomexa** [comment]
I was blocked by this problem too and found my solution here :)
I add a mongo validation error because every field of my body that were objects were renered as [object Object].
You should add the use case with the :[Object] in your Readme ;)

**Comment by tomgekeerd** [comment]
Got this issue as well, but finally fixed it here. Would there be another solution to add required checks to the object parameters, maybe?
