### ISSUE TITLE
How to make validations?

### ISSUE THREAD

**Issue by nassibullin** [diegohaz/bodymen#17]
I want to create validation for phoneNumber
`phoneNumber:{
        type: String,
        validate: /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/
    }`
or to choose validate that value equals only one of provided
`productType: {
type: String,
validate: ['bread', 'milk']
}`

**Comment by diegohaz** [comment]
This project follows the same rules as [Mongoose](http://mongoosejs.com/docs/validation.html) (check out their docs).

In that case, it will be:
```js
{
  phoneNumber: {
    type: String,
    match: /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/,
  },
  productType: {
    type: String,
    enum: ['bread', 'milk']
  }
}
```

`validate` accepts a function. You can use it to create custom validations.
