### ISSUE TITLE
A required field should be ignored in case of update

### ISSUE THREAD

**Issue by thxmxx** [diegohaz/bodymen#18]
Most of the time the Required statement is only applicable for creating the documents. After creation I cannot force the user to fill these fields again. Is there any option to bypass this?

I am copying the schema tree

```
const schemaTree = schema.tree
delete schemaTree._id;
delete schemaTree.updatedAt;
delete schemaTree.createdAt;
delete schemaTree.__v;

router.put('/:id',
  body( schemaTree ),
  update)
```

**Comment by diegohaz** [comment]
You can override the option when passing the object to `body`:
```js
body({ ...schemaTree, field: { ...scemaTree.field, required: false } })
```

**Comment by Mustafax06** [comment]
Do I have to do this to all fields? Can I just override them all at once?
